package shepherd

import (
	"bytes"
	"encoding/json"
	"math"
	"os"
	"strings"
	"testing"
)

// These vectors are generated by the Python reference implementation, not by Go.
//
// Generator: `testdata/generate_canonical_edge_vectors.py`, which imports the real
// `shepherd2.kernel.canonical` so the expected bytes come from the authoritative
// `canonical_json_bytes` / `canonical_digest` rather than a reimplementation. The
// file records the source commit and Python version. Regenerate with:
//
//	python testdata/generate_canonical_edge_vectors.py testdata/canonical_edge_vectors_v0.json
//
// That needs the Python checkout (see SHEPHERD2_SRC in the script). Regenerating
// changes the file's hash, so update the pinned value in golden_provenance_test.go
// in the same commit. Verified reproducible: the vendored generator reproduces all
// 42 vectors byte-for-byte.
//
// They exist because the digest layer's whole contract is cross-implementation
// byte-identity, and every historical divergence in it — HTML escaping of <, >,
// &, and Python's float repr — was invisible to the shared golden file, whose
// payloads happen to contain only small ints and plain ASCII.
type canonicalVector struct {
	Label          string         `json:"label"`
	Payload        map[string]any `json:"payload"`
	CanonicalBytes string         `json:"canonical_bytes"`
	Digest         string         `json:"digest"`
}

type canonicalVectorFile struct {
	CanonicalVersion string            `json:"canonical_version"`
	Generator        string            `json:"generator"`
	SourceRepo       string            `json:"source_repo"`
	SourceCommit     string            `json:"source_commit"`
	PythonVersion    string            `json:"python_version"`
	EdgeFloats       []canonicalVector `json:"edge_floats"`
	EdgeStrings      []canonicalVector `json:"edge_strings"`
	Mixed            []canonicalVector `json:"mixed"`
}

func (f canonicalVectorFile) all() []canonicalVector {
	var out []canonicalVector
	for _, group := range [][]canonicalVector{f.EdgeFloats, f.EdgeStrings, f.Mixed} {
		out = append(out, group...)
	}
	return out
}

// loadEdgeVectors reads the Python-generated vectors, preserving number text.
//
// UseNumber matters here for the same reason it matters in the kernel: the
// difference between JSON `1` and `1.0` is the difference between canonical
// "1" and "1.0", and only the token text carries it.
func loadEdgeVectors(t *testing.T) canonicalVectorFile {
	t.Helper()
	data, err := os.ReadFile("testdata/canonical_edge_vectors_v0.json")
	if err != nil {
		t.Fatalf("read edge vectors: %v", err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var doc canonicalVectorFile
	if err := dec.Decode(&doc); err != nil {
		t.Fatalf("parse edge vectors: %v", err)
	}
	return doc
}

// TestCanonicalEdgeVectorsMatchPython is the acceptance test for plan 01 §1:
// payloads with <, >, &, and floats across the notation boundary must produce
// bytes and digests identical to Python's.
func TestCanonicalEdgeVectorsMatchPython(t *testing.T) {
	doc := loadEdgeVectors(t)

	if doc.CanonicalVersion != CanonicalVersion {
		t.Errorf("vector file canonical_version = %q, want %q", doc.CanonicalVersion, CanonicalVersion)
	}
	// HasPrefix, not ==: the generator's git_commit swallows every failure and
	// returns "unknown (<exc>)", which an equality check against "unknown"
	// would let through — a corpus regenerated without a usable Python
	// checkout would then pass with provenance that names nothing. The corpus
	// test checks the same way.
	if doc.SourceCommit == "" || strings.HasPrefix(doc.SourceCommit, "unknown") {
		t.Error("vector file has no source_commit, so the vectors cannot be traced to a revision")
	}

	vectors := doc.all()
	if len(vectors) == 0 {
		t.Fatal("vector file contains no vectors")
	}
	t.Logf("checking %d vectors from shepherd2@%.12s (Python %s)",
		len(vectors), doc.SourceCommit, doc.PythonVersion)

	for _, v := range vectors {
		t.Run(v.Label, func(t *testing.T) {
			got, err := CanonicalJSONBytes(v.Payload)
			if err != nil {
				t.Fatalf("CanonicalJSONBytes: %v", err)
			}
			if string(got) != v.CanonicalBytes {
				t.Errorf("canonical bytes differ from Python\n got: %s\nwant: %s",
					string(got), v.CanonicalBytes)
			}

			digest, err := CanonicalDigest(v.Payload)
			if err != nil {
				t.Fatalf("CanonicalDigest: %v", err)
			}
			if digest != v.Digest {
				t.Errorf("digest differs from Python\n got: %s\nwant: %s", digest, v.Digest)
			}
		})
	}
}

// TestCanonicalEdgeVectorsCoverTheKnownDivergences guards against the vector file
// being regenerated with a weaker payload set, which would quietly re-open the
// holes this test was added to close.
func TestCanonicalEdgeVectorsCoverTheKnownDivergences(t *testing.T) {
	doc := loadEdgeVectors(t)

	joined := new(strings.Builder)
	for _, v := range doc.all() {
		joined.WriteString(v.CanonicalBytes)
		joined.WriteByte('\n')
	}
	all := joined.String()

	for _, needle := range []string{"<", ">", "&", "0.0", "-0.0", "1e+16", "1e-05", "\\u0007"} {
		if !strings.Contains(all, needle) {
			t.Errorf("vector set no longer exercises %q; the divergence it was added for is untested", needle)
		}
	}
}

// TestFormatCanonicalFloatRejectsNonFinite pins that NaN and infinities error
// rather than emitting a token, mirroring json.dumps(allow_nan=False).
func TestFormatCanonicalFloatRejectsNonFinite(t *testing.T) {
	for _, f := range []float64{math.NaN(), math.Inf(1), math.Inf(-1)} {
		if _, err := formatCanonicalFloat(f); err == nil {
			t.Errorf("formatCanonicalFloat(%v) succeeded, want an error", f)
		}
	}
	if _, err := CanonicalJSONBytes(map[string]any{"v": math.NaN()}); err == nil {
		t.Error("canonical JSON accepted NaN; Python's allow_nan=False would not")
	}
}

// TestCanonicalJSONRejectsUnsupportedType pins the deliberate change from a
// json.Marshal fallback to an error: a silent fallback is how the escaping
// divergence survived, because it produced a plausible digest over other bytes.
func TestCanonicalJSONRejectsUnsupportedType(t *testing.T) {
	type custom struct{ A int }
	_, err := CanonicalJSONBytes(map[string]any{"v": custom{A: 1}})
	if err == nil {
		t.Fatal("canonical JSON accepted a struct; unsupported types must error")
	}
	if !strings.Contains(err.Error(), "unsupported type") {
		t.Errorf("err = %v, want it to name the unsupported type", err)
	}
}

// TestCanonicalJSONStringEscaping pins the escaper directly. Every expected
// value is the exact output of CPython 3.13's
// json.dumps(..., ensure_ascii=False, separators=(",",":"), sort_keys=True).
func TestCanonicalJSONStringEscaping(t *testing.T) {
	cases := []struct {
		name  string
		input string
		want  string
	}{
		// Must NOT be HTML-escaped: this is the divergence that motivated the
		// hand-written escaper.
		{"html_raw", "<script>a&&b</script>", `{"v":"<script>a&&b</script>"}`},
		{"quotes_backslash_slash", `a"b\c/d`, `{"v":"a\"b\\c/d"}`},
		{"short_escapes", "\b\f\n\r\t", `{"v":"\b\f\n\r\t"}`},
		// Vertical tab has no short form; all low controls use lowercase hex.
		{"low_control_hex", "\x00\x07\x0b\x1b\x1f", `{"v":"\u0000\u0007\u000b\u001b\u001f"}`},
		{"non_ascii_raw_utf8", "café", `{"v":"café"}`},
		{"emoji_raw_utf8", "\U0001F600", `{"v":"😀"}`},
		// Go's encoding/json escapes these unconditionally; Python does not.
		{"line_para_sep_raw", "\u2028\u2029", `{"v":"` + "\u2028\u2029" + `"}`},
		// DEL is emitted literally when ensure_ascii=False.
		{"del_raw", "\x7f", `{"v":"` + "\x7f" + `"}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := CanonicalJSONBytes(map[string]any{"v": tc.input})
			if err != nil {
				t.Fatalf("CanonicalJSONBytes: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got  %q\nwant %q", string(got), tc.want)
			}
		})
	}
}

// TestCanonicalJSONRejectsInvalidUTF8 pins the failure mode for a Go string that
// is not valid UTF-8.
//
// CPython raises UnicodeEncodeError when it encodes the result as UTF-8, so
// rejecting mirrors an existing failure. Passing the bytes through would emit
// invalid JSON, and substituting U+FFFD the way encoding/json does would digest a
// string the caller never held — both silent.
func TestCanonicalJSONRejectsInvalidUTF8(t *testing.T) {
	bad := []struct {
		name string
		in   string
	}{
		{"lone continuation byte", string([]byte{0xff})},
		{"truncated sequence", string([]byte{0xe2, 0x98})},
		{"utf8 encoding of a surrogate", string([]byte{0xed, 0xa0, 0x80})},
	}
	for _, tc := range bad {
		t.Run(tc.name, func(t *testing.T) {
			_, err := CanonicalJSONBytes(map[string]any{"v": tc.in})
			if err == nil {
				t.Fatalf("accepted invalid UTF-8 % x, want an error", []byte(tc.in))
			}
			if !strings.Contains(err.Error(), "valid UTF-8") {
				t.Errorf("err = %v, want it to name the encoding problem", err)
			}
		})
	}

	// And the same bytes in a key, which is a separate call site.
	if _, err := CanonicalJSONBytes(map[string]any{string([]byte{0xff}): 1}); err == nil {
		t.Error("accepted an invalid UTF-8 map key, want an error")
	}
}

// TestCanonicalJSONNumberTokenValidation pins that json.Number text is checked
// against the JSON grammar and normalised the way Python normalises it.
//
// json.Number carries caller-supplied text, and strconv.ParseFloat is looser than
// JSON — it accepts "Inf", "NaN" and digit separators — so without validation a
// malformed token would reach digest input as invalid JSON, or be accepted where
// Python's json.loads rejects it.
func TestCanonicalJSONNumberTokenValidation(t *testing.T) {
	accepted := []struct {
		in   string
		want string
	}{
		{"0", "0"},
		{"-0", "0"}, // Python parses -0 as the integer 0 and re-serialises "0"
		{"1", "1"},
		{"-1", "-1"},
		{"1.5", "1.5"},
		{"1e2", "100.0"},  // a float token is rendered as a float
		{"1E2", "100.0"},  //
		{"-0.0", "-0.0"},  // a float token keeps its sign
		{"1e-5", "1e-05"}, //
		{"0.0001", "0.0001"},
		{"123456789012345678901234567890", "123456789012345678901234567890"}, // beyond float64
	}
	for _, tc := range accepted {
		t.Run("accept "+tc.in, func(t *testing.T) {
			got, err := CanonicalJSONBytes(map[string]any{"v": json.Number(tc.in)})
			if err != nil {
				t.Fatalf("json.Number(%q): %v", tc.in, err)
			}
			want := `{"v":` + tc.want + `}`
			if string(got) != want {
				t.Errorf("json.Number(%q) -> %s, want %s", tc.in, string(got), want)
			}
		})
	}

	rejected := []string{"01", "+1", "1.", ".5", "", "-", "1e", "1e+", "Inf", "NaN", "infinity", "1_000", "0x10"}
	for _, in := range rejected {
		t.Run("reject "+in, func(t *testing.T) {
			if _, err := CanonicalJSONBytes(map[string]any{"v": json.Number(in)}); err == nil {
				t.Errorf("accepted json.Number(%q), want an error", in)
			}
		})
	}
}

// TestCanonicalJSONDetectsCycles pins that a self-referential container is
// reported rather than overflowing the stack.
//
// CPython's json.dumps raises "Circular reference detected" for both dict and
// list cycles. Detection tracks ancestors rather than everything visited, so a
// value reachable by two paths is not mistaken for a cycle — asserted below,
// because a naive visited-set would reject it.
func TestCanonicalJSONDetectsCycles(t *testing.T) {
	t.Run("map cycle", func(t *testing.T) {
		m := map[string]any{}
		m["self"] = m
		_, err := CanonicalJSONBytes(m)
		if err == nil {
			t.Fatal("accepted a self-referential map")
		}
		if !strings.Contains(err.Error(), "circular") {
			t.Errorf("err = %v, want it to name the cycle", err)
		}
	})

	t.Run("slice cycle", func(t *testing.T) {
		s := make([]any, 1)
		s[0] = s
		if _, err := CanonicalJSONBytes(s); err == nil {
			t.Fatal("accepted a self-referential slice")
		}
	})

	t.Run("indirect cycle", func(t *testing.T) {
		a := map[string]any{}
		b := map[string]any{"a": a}
		a["b"] = b
		if _, err := CanonicalJSONBytes(a); err == nil {
			t.Fatal("accepted an indirect cycle")
		}
	})

	t.Run("shared value is not a cycle", func(t *testing.T) {
		shared := map[string]any{"x": 1}
		got, err := CanonicalJSONBytes(map[string]any{"a": shared, "b": shared})
		if err != nil {
			t.Fatalf("a value reachable by two paths was reported as a cycle: %v", err)
		}
		if want := `{"a":{"x":1},"b":{"x":1}}`; string(got) != want {
			t.Errorf("got %s, want %s", string(got), want)
		}
	})
}

type canonicalNamedPorts []int

// TestCanonicalJSONAcceptsTypedContainers pins that JSON-compatible typed
// containers keep working.
//
// The public payload API does not require callers to convert every slice to
// []any, and rejecting them would break existing callers — the error path exists
// for types JSON genuinely cannot represent, not for typed containers. Nil
// containers become null, which is what encoding/json produced before.
func TestCanonicalJSONAcceptsTypedContainers(t *testing.T) {
	one := 1
	cases := []struct {
		name string
		in   map[string]any
		want string
	}{
		{"int slice", map[string]any{"ports": []int{80, 443}}, `{"ports":[80,443]}`},
		{"named slice type", map[string]any{"ports": canonicalNamedPorts{80, 443}}, `{"ports":[80,443]}`},
		{"typed map", map[string]any{"m": map[string]int{"b": 2, "a": 1}}, `{"m":{"a":1,"b":2}}`},
		{"float slice", map[string]any{"f": []float64{1, 2.5}}, `{"f":[1.0,2.5]}`},
		{"bool slice", map[string]any{"b": []bool{true, false}}, `{"b":[true,false]}`},
		{"nested typed", map[string]any{"m": map[string][]int{"k": {1, 2}}}, `{"m":{"k":[1,2]}}`},
		{"array", map[string]any{"a": [2]int{1, 2}}, `{"a":[1,2]}`},
		{"nil slice", map[string]any{"v": []int(nil)}, `{"v":null}`},
		{"nil typed map", map[string]any{"v": map[string]int(nil)}, `{"v":null}`},
		{"pointer", map[string]any{"v": &one}, `{"v":1}`},
		{"nil pointer", map[string]any{"v": (*int)(nil)}, `{"v":null}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := CanonicalJSONBytes(tc.in)
			if err != nil {
				t.Fatalf("CanonicalJSONBytes: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got  %s\nwant %s", string(got), tc.want)
			}
		})
	}

	// A non-string map key is still an error, which is the restriction that
	// actually matters for canonical output.
	t.Run("non-string map key", func(t *testing.T) {
		_, err := CanonicalJSONBytes(map[string]any{"m": map[int]string{1: "a"}})
		if err == nil {
			t.Fatal("accepted a map with non-string keys")
		}
		if !strings.Contains(err.Error(), "keys must be strings") {
			t.Errorf("err = %v, want it to name the key restriction", err)
		}
	})
}
