package shepherd

import (
	"bytes"
	"encoding/json"
	"math"
	"os"
	"strings"
	"testing"
)

// These vectors are generated by the Python reference implementation, not by Go.
//
// Generator: `generate_canonical_edge_vectors.py`, run against
// `../shepherd/shepherd2`, importing the real `shepherd2.kernel.canonical` so the
// expected bytes come from the authoritative `canonical_json_bytes` /
// `canonical_digest` rather than a reimplementation. The file records the source
// commit and Python version; regenerate with:
//
//	python gen_canonical_edge_vectors.py testdata/canonical_edge_vectors_v0.json
//
// They exist because the digest layer's whole contract is cross-implementation
// byte-identity, and every historical divergence in it — HTML escaping of <, >,
// &, and Python's float repr — was invisible to the shared golden file, whose
// payloads happen to contain only small ints and plain ASCII.
type canonicalVector struct {
	Label          string         `json:"label"`
	Payload        map[string]any `json:"payload"`
	CanonicalBytes string         `json:"canonical_bytes"`
	Digest         string         `json:"digest"`
}

type canonicalVectorFile struct {
	CanonicalVersion string            `json:"canonical_version"`
	Generator        string            `json:"generator"`
	SourceRepo       string            `json:"source_repo"`
	SourceCommit     string            `json:"source_commit"`
	PythonVersion    string            `json:"python_version"`
	EdgeFloats       []canonicalVector `json:"edge_floats"`
	EdgeStrings      []canonicalVector `json:"edge_strings"`
	Mixed            []canonicalVector `json:"mixed"`
}

func (f canonicalVectorFile) all() []canonicalVector {
	var out []canonicalVector
	for _, group := range [][]canonicalVector{f.EdgeFloats, f.EdgeStrings, f.Mixed} {
		out = append(out, group...)
	}
	return out
}

// loadEdgeVectors reads the Python-generated vectors, preserving number text.
//
// UseNumber matters here for the same reason it matters in the kernel: the
// difference between JSON `1` and `1.0` is the difference between canonical
// "1" and "1.0", and only the token text carries it.
func loadEdgeVectors(t *testing.T) canonicalVectorFile {
	t.Helper()
	data, err := os.ReadFile("testdata/canonical_edge_vectors_v0.json")
	if err != nil {
		t.Fatalf("read edge vectors: %v", err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var doc canonicalVectorFile
	if err := dec.Decode(&doc); err != nil {
		t.Fatalf("parse edge vectors: %v", err)
	}
	return doc
}

// TestCanonicalEdgeVectorsMatchPython is the acceptance test for plan 01 §1:
// payloads with <, >, &, and floats across the notation boundary must produce
// bytes and digests identical to Python's.
func TestCanonicalEdgeVectorsMatchPython(t *testing.T) {
	doc := loadEdgeVectors(t)

	if doc.CanonicalVersion != CanonicalVersion {
		t.Errorf("vector file canonical_version = %q, want %q", doc.CanonicalVersion, CanonicalVersion)
	}
	if doc.SourceCommit == "" || doc.SourceCommit == "unknown" {
		t.Error("vector file has no source_commit, so the vectors cannot be traced to a revision")
	}

	vectors := doc.all()
	if len(vectors) == 0 {
		t.Fatal("vector file contains no vectors")
	}
	t.Logf("checking %d vectors from shepherd2@%.12s (Python %s)",
		len(vectors), doc.SourceCommit, doc.PythonVersion)

	for _, v := range vectors {
		t.Run(v.Label, func(t *testing.T) {
			got, err := CanonicalJSONBytes(v.Payload)
			if err != nil {
				t.Fatalf("CanonicalJSONBytes: %v", err)
			}
			if string(got) != v.CanonicalBytes {
				t.Errorf("canonical bytes differ from Python\n got: %s\nwant: %s",
					string(got), v.CanonicalBytes)
			}

			digest, err := CanonicalDigest(v.Payload)
			if err != nil {
				t.Fatalf("CanonicalDigest: %v", err)
			}
			if digest != v.Digest {
				t.Errorf("digest differs from Python\n got: %s\nwant: %s", digest, v.Digest)
			}
		})
	}
}

// TestCanonicalEdgeVectorsCoverTheKnownDivergences guards against the vector file
// being regenerated with a weaker payload set, which would quietly re-open the
// holes this test was added to close.
func TestCanonicalEdgeVectorsCoverTheKnownDivergences(t *testing.T) {
	doc := loadEdgeVectors(t)

	joined := new(strings.Builder)
	for _, v := range doc.all() {
		joined.WriteString(v.CanonicalBytes)
		joined.WriteByte('\n')
	}
	all := joined.String()

	for _, needle := range []string{"<", ">", "&", "0.0", "-0.0", "1e+16", "1e-05", "\\u0007"} {
		if !strings.Contains(all, needle) {
			t.Errorf("vector set no longer exercises %q; the divergence it was added for is untested", needle)
		}
	}
}

// TestFormatCanonicalFloatRejectsNonFinite pins that NaN and infinities error
// rather than emitting a token, mirroring json.dumps(allow_nan=False).
func TestFormatCanonicalFloatRejectsNonFinite(t *testing.T) {
	for _, f := range []float64{math.NaN(), math.Inf(1), math.Inf(-1)} {
		if _, err := formatCanonicalFloat(f); err == nil {
			t.Errorf("formatCanonicalFloat(%v) succeeded, want an error", f)
		}
	}
	if _, err := CanonicalJSONBytes(map[string]any{"v": math.NaN()}); err == nil {
		t.Error("canonical JSON accepted NaN; Python's allow_nan=False would not")
	}
}

// TestCanonicalJSONRejectsUnsupportedType pins the deliberate change from a
// json.Marshal fallback to an error: a silent fallback is how the escaping
// divergence survived, because it produced a plausible digest over other bytes.
func TestCanonicalJSONRejectsUnsupportedType(t *testing.T) {
	type custom struct{ A int }
	_, err := CanonicalJSONBytes(map[string]any{"v": custom{A: 1}})
	if err == nil {
		t.Fatal("canonical JSON accepted a struct; unsupported types must error")
	}
	if !strings.Contains(err.Error(), "unsupported type") {
		t.Errorf("err = %v, want it to name the unsupported type", err)
	}
}

// TestCanonicalJSONStringEscaping pins the escaper directly. Every expected
// value is the exact output of CPython 3.13's
// json.dumps(..., ensure_ascii=False, separators=(",",":"), sort_keys=True).
func TestCanonicalJSONStringEscaping(t *testing.T) {
	cases := []struct {
		name  string
		input string
		want  string
	}{
		// Must NOT be HTML-escaped: this is the divergence that motivated the
		// hand-written escaper.
		{"html_raw", "<script>a&&b</script>", `{"v":"<script>a&&b</script>"}`},
		{"quotes_backslash_slash", `a"b\c/d`, `{"v":"a\"b\\c/d"}`},
		{"short_escapes", "\b\f\n\r\t", `{"v":"\b\f\n\r\t"}`},
		// Vertical tab has no short form; all low controls use lowercase hex.
		{"low_control_hex", "\x00\x07\x0b\x1b\x1f", `{"v":"\u0000\u0007\u000b\u001b\u001f"}`},
		{"non_ascii_raw_utf8", "café", `{"v":"café"}`},
		{"emoji_raw_utf8", "\U0001F600", `{"v":"😀"}`},
		// Go's encoding/json escapes these unconditionally; Python does not.
		{"line_para_sep_raw", "\u2028\u2029", `{"v":"` + "\u2028\u2029" + `"}`},
		// DEL is emitted literally when ensure_ascii=False.
		{"del_raw", "\x7f", `{"v":"` + "\x7f" + `"}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := CanonicalJSONBytes(map[string]any{"v": tc.input})
			if err != nil {
				t.Fatalf("CanonicalJSONBytes: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("got  %q\nwant %q", string(got), tc.want)
			}
		})
	}
}
