package shepherd

// Execution schema tests (plan 02 §1), measured against
// testdata/execution_vectors_v0.json, which was generated by
// testdata/generate_execution_vectors.py against the reference
// implementation at shepherd2@d34d5ca3. Regenerate with:

//	python testdata/generate_execution_vectors.py testdata/execution_vectors_v0.json

// and update the pinned hash in golden_provenance_test.go in the same commit.

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
)

type executionIDVector struct {
	AppendIntentID string `json:"append_intent_id"`
	LocalRef       string `json:"local_ref"`
	ExecutionID    string `json:"execution_id"`
}

type relationIDVector struct {
	AppendIntentID string `json:"append_intent_id"`
	LocalRef       string `json:"local_ref"`
	RelationID     string `json:"relation_id"`
}

type publishedFactVector struct {
	SchemaRef string         `json:"schema_ref"`
	KindLabel string         `json:"kind_label"`
	Mode      string         `json:"mode"`
	Payload   map[string]any `json:"payload"`
}

type executionVectorFact struct {
	FactID    string `json:"fact_id"`
	SchemaRef string `json:"schema_ref"`
	Mode      string `json:"mode"`
	KindLabel string `json:"kind_label"`
}

type executionVectorCutoff struct {
	FrontierID          string `json:"frontier_id"`
	TargetTraceOwnerID  string `json:"target_trace_owner_id"`
	ThroughFactID       string `json:"through_fact_id"`
	ThroughOwnerOrdinal int    `json:"through_owner_ordinal"`
	PublisherOwnerID    string `json:"publisher_trace_owner_id"`
	CreatedByFactID     string `json:"created_by_fact_id"`
}

type executionVectorStep struct {
	Kind           string         `json:"kind"`
	AppendIntentID string         `json:"append_intent_id"`
	FrontierID     string         `json:"frontier_id"`
	ThroughFactID  string         `json:"through_fact_id"`
	Payload        map[string]any `json:"payload"`
	Outputs        map[string]any `json:"outputs"`
	Error          string         `json:"error"`
	FactIDs        []string       `json:"fact_ids"`
}

type executionVectorRun struct {
	RunID       string                `json:"run_id"`
	ExecutionID string                `json:"execution_id"`
	FrontierID  string                `json:"frontier_id"`
	TaskRef     string                `json:"task_ref"`
	Inputs      map[string]any        `json:"inputs"`
	Steps       []executionVectorStep `json:"steps"`
	OwnerPath   []executionVectorFact `json:"owner_path"`
	Cutoff      executionVectorCutoff `json:"cutoff"`
}

type executionVectorRelation struct {
	ParentRunID         string         `json:"parent_run_id"`
	ChildRunID          string         `json:"child_run_id"`
	ParentExecutionID   string         `json:"parent_execution_id"`
	ChildExecutionID    string         `json:"child_execution_id"`
	ChildFrontierID     string         `json:"child_frontier_id"`
	RelationIntent      string         `json:"relation_intent"`
	RelationID          string         `json:"relation_id"`
	ParentCreateIntent  string         `json:"parent_create_intent"`
	ParentTaskRef       string         `json:"parent_task_ref"`
	ChildCreateIntent   string         `json:"child_create_intent"`
	ChildTaskRef        string         `json:"child_task_ref"`
	ChildInputs         map[string]any `json:"child_inputs"`
	ChildCompleteIntent string         `json:"child_complete_intent"`
	ChildOutputs        map[string]any `json:"child_outputs"`
	RelationFactID      string         `json:"relation_fact_id"`
}

type executionVectorDoc struct {
	Generator        string                  `json:"generator"`
	SourceRepo       string                  `json:"source_repo"`
	SourceCommit     string                  `json:"source_commit"`
	PythonVersion    string                  `json:"python_version"`
	ExecutionIDs     []executionIDVector     `json:"execution_ids"`
	RelationIDs      []relationIDVector      `json:"relation_ids"`
	PublishedFact    publishedFactVector     `json:"published_fact"`
	RunSequence      executionVectorRun      `json:"run_sequence"`
	FailSequence     executionVectorRun      `json:"fail_sequence"`
	RelationSequence executionVectorRelation `json:"relation_sequence"`
	HistorySequence  executionVectorHistory  `json:"history_sequence"`
}

func loadExecutionVectors(t *testing.T) executionVectorDoc {
	t.Helper()
	data, err := os.ReadFile("testdata/execution_vectors_v0.json")
	if err != nil {
		t.Fatalf("read execution vectors: %v", err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var doc executionVectorDoc
	if err := dec.Decode(&doc); err != nil {
		t.Fatalf("parse execution vectors: %v", err)
	}
	return doc
}

// TestExecutionIDForMatchesPython pins the derivation against the reference:
// plain sha256 over "<intent>\0<local_ref>", not canonical JSON.
func TestExecutionIDForMatchesPython(t *testing.T) {
	doc := loadExecutionVectors(t)
	for _, v := range doc.ExecutionIDs {
		if got := ExecutionIDFor(v.AppendIntentID, v.LocalRef); got != v.ExecutionID {
			t.Errorf("ExecutionIDFor(%q, %q) = %s, want %s", v.AppendIntentID, v.LocalRef, got, v.ExecutionID)
		}
	}
}

// TestExecutionDraftShapes pins the four lifecycle drafts: mode, schema,
// kind label and payload keys, including parent_execution_id as JSON null
// when absent — "" would digest differently.
func TestExecutionDraftShapes(t *testing.T) {
	created := ExecutionCreatedDraft("exec:abc", "Task", map[string]any{"x": 1}, "")
	if created.Mode != Declaration || created.SchemaRef != SchemaExecutionCreated || created.KindLabel != "execution_created" {
		t.Errorf("created draft: %+v", created)
	}
	if created.Payload["execution_id"] != "exec:abc" || created.Payload["task_ref"] != "Task" {
		t.Errorf("created payload: %v", created.Payload)
	}
	if v := created.Payload["parent_execution_id"]; v != nil {
		t.Errorf("absent parent must be JSON null, got %v", v)
	}

	withParent := ExecutionCreatedDraft("exec:abc", "Task", nil, "exec:parent")
	if v := withParent.Payload["parent_execution_id"]; v != "exec:parent" {
		t.Errorf("parent link = %v, want exec:parent", v)
	}

	started := ExecutionStartedDraft("exec:abc")
	if started.Mode != Capture || started.SchemaRef != SchemaExecutionStarted || started.KindLabel != "execution_started" {
		t.Errorf("started draft: %+v", started)
	}

	completed := ExecutionCompletedDraft("exec:abc", map[string]any{"ok": true})
	if completed.Mode != Capture || completed.SchemaRef != SchemaExecutionCompleted || completed.KindLabel != "execution_completed" {
		t.Errorf("completed draft: %+v", completed)
	}
	if completed.Payload["outputs"] == nil {
		t.Error("completed payload must carry outputs")
	}

	failed := ExecutionFailedDraft("exec:abc", "boom")
	if failed.Mode != Capture || failed.SchemaRef != SchemaExecutionFailed || failed.KindLabel != "execution_failed" {
		t.Errorf("failed draft: %+v", failed)
	}
	if failed.Payload["error"] != "boom" {
		t.Errorf("failed payload error = %v", failed.Payload["error"])
	}
}

// replayExecutionVector replays a vector's recorded steps through the Go
// store using the same batch builders and the runtime's causal wiring
// (publish caused-by the tail; complete/fail caused-by the tail; the frontier
// through the terminal fact), so the allocated ids can be compared with the
// reference's.
func replayExecutionVector(t *testing.T, doc executionVectorDoc, vec executionVectorRun) *SQLiteTraceStore {
	t.Helper()
	store := newMemStore(t)
	publishSchema := doc.PublishedFact.SchemaRef

	var causalTail string
	var terminalFactID string
	for _, step := range vec.Steps {
		switch step.Kind {
		case "create":
			receipt, err := store.Append(TrustedAppendContext, CreateExecutionBatch(
				step.AppendIntentID, vec.ExecutionID, vec.TaskRef, vec.Inputs, "", nil,
			))
			if err != nil {
				t.Fatalf("replay create: %v", err)
			}
			causalTail = receipt.FactIDs[len(receipt.FactIDs)-1]
		case "publish":
			receipt, err := store.Append(TrustedAppendContext, AppendBatch{
				AppendIntentID: step.AppendIntentID,
				Groups: []AppendGroup{{
					TraceOwnerID:  vec.ExecutionID,
					CausalParents: []string{causalTail},
					FactDrafts: []RecordDraft{{
						Mode:      Capture,
						SchemaRef: publishSchema,
						KindLabel: "fact_published",
						Payload:   step.Payload,
					}},
				}},
			})
			if err != nil {
				t.Fatalf("replay publish: %v", err)
			}
			causalTail = receipt.FactIDs[len(receipt.FactIDs)-1]
		case "complete":
			receipt, err := store.Append(TrustedAppendContext, CompleteExecutionBatch(
				step.AppendIntentID, vec.ExecutionID, step.Outputs, []string{causalTail},
			))
			if err != nil {
				t.Fatalf("replay complete: %v", err)
			}
			terminalFactID = receipt.FactIDs[len(receipt.FactIDs)-1]
		case "fail":
			receipt, err := store.Append(TrustedAppendContext, FailExecutionBatch(
				step.AppendIntentID, vec.ExecutionID, step.Error, []string{causalTail},
			))
			if err != nil {
				t.Fatalf("replay fail: %v", err)
			}
			terminalFactID = receipt.FactIDs[len(receipt.FactIDs)-1]
		case "frontier":
			_, err := PublishExecutionFrontier(store, TrustedAppendContext,
				step.FrontierID, vec.ExecutionID, terminalFactID, "", "", nil)
			if err != nil {
				t.Fatalf("replay frontier: %v", err)
			}
		default:
			t.Fatalf("unknown vector step kind %q", step.Kind)
		}
	}
	return store
}

// TestExecutionVectorRunSequenceReplay replays the Python @task run's
// recorded steps and must allocate identical fact ids and terminal cutoff.
func TestExecutionVectorRunSequenceReplay(t *testing.T) {
	doc := loadExecutionVectors(t)
	vec := doc.RunSequence
	if vec.ExecutionID != ExecutionIDFor(vec.RunID+":create", "execution") {
		t.Fatalf("vector execution id disagrees with the derivation: %s", vec.ExecutionID)
	}

	store := replayExecutionVector(t, doc, vec)

	slice, err := store.ReadOwnerPrefix(reader, vec.ExecutionID, 99, ModeBoth)
	if err != nil {
		t.Fatalf("ReadOwnerPrefix: %v", err)
	}
	if len(slice.FactIDs()) != len(vec.OwnerPath) {
		t.Fatalf("owner path has %d facts, want %d: %v", len(slice.FactIDs()), len(vec.OwnerPath), slice.FactIDs())
	}
	for i, fact := range vec.OwnerPath {
		if slice.FactIDs()[i] != fact.FactID {
			t.Errorf("owner path[%d] = %s, want %s (%s)", i, slice.FactIDs()[i], fact.FactID, fact.SchemaRef)
		}
		visible := slice.FactsByID[fact.FactID]
		rec, ok := visible.(Record)
		if !ok {
			t.Fatalf("fact %s is not payload-visible", fact.FactID)
		}
		if rec.Envelope.SchemaRef != fact.SchemaRef {
			t.Errorf("fact[%d] schema = %s, want %s", i, rec.Envelope.SchemaRef, fact.SchemaRef)
		}
		if string(rec.Envelope.Mode) != fact.Mode {
			t.Errorf("fact[%d] mode = %s, want %s", i, rec.Envelope.Mode, fact.Mode)
		}
	}

	cutoff, err := store.ReadOwnerCutoff(vec.FrontierID)
	if err != nil {
		t.Fatalf("ReadOwnerCutoff: %v", err)
	}
	want := vec.Cutoff
	if cutoff.FrontierID != want.FrontierID ||
		cutoff.TargetTraceOwnerID != want.TargetTraceOwnerID ||
		cutoff.ThroughFactID != want.ThroughFactID ||
		cutoff.ThroughOwnerOrdinal != want.ThroughOwnerOrdinal ||
		cutoff.PublisherOwnerID != want.PublisherOwnerID ||
		cutoff.CreatedByFactID != want.CreatedByFactID {
		t.Errorf("cutoff = %+v, want %+v", cutoff, want)
	}

	// The fold must agree with the vector's recorded terminal state.
	exec, err := ProjectExecutionFromStore(store, reader, cutoff)
	if err != nil {
		t.Fatalf("ProjectExecutionFromStore: %v", err)
	}
	if exec.Status != ExecutionSucceeded {
		t.Errorf("status = %s, want succeeded", exec.Status)
	}
	if exec.TaskRef != vec.TaskRef {
		t.Errorf("task_ref = %s, want %s", exec.TaskRef, vec.TaskRef)
	}
	if exec.TerminalFactID != want.ThroughFactID {
		t.Errorf("terminal fact = %s, want %s", exec.TerminalFactID, want.ThroughFactID)
	}
	if n, ok := exec.Outputs["answer"].(json.Number); !ok || n.String() != "42" {
		t.Errorf("outputs[answer] = %v (%T), want json.Number 42", exec.Outputs["answer"], exec.Outputs["answer"])
	}
	if exec.Outputs["label"] != "ok" {
		t.Errorf("outputs[label] = %v, want ok", exec.Outputs["label"])
	}
}

// TestExecutionVectorFailSequenceReplay replays the create→fail→frontier
// sequence and must allocate identical ids, with a failed fold.
func TestExecutionVectorFailSequenceReplay(t *testing.T) {
	doc := loadExecutionVectors(t)
	vec := doc.FailSequence

	store := replayExecutionVector(t, doc, vec)

	slice, err := store.ReadOwnerPrefix(reader, vec.ExecutionID, 99, ModeBoth)
	if err != nil {
		t.Fatalf("ReadOwnerPrefix: %v", err)
	}
	if len(slice.FactIDs()) != len(vec.OwnerPath) {
		t.Fatalf("owner path has %d facts, want %d", len(slice.FactIDs()), len(vec.OwnerPath))
	}
	for i, fact := range vec.OwnerPath {
		if slice.FactIDs()[i] != fact.FactID {
			t.Errorf("owner path[%d] = %s, want %s", i, slice.FactIDs()[i], fact.FactID)
		}
	}

	cutoff, err := store.ReadOwnerCutoff(vec.FrontierID)
	if err != nil {
		t.Fatalf("ReadOwnerCutoff: %v", err)
	}
	want := vec.Cutoff
	if cutoff.ThroughFactID != want.ThroughFactID || cutoff.ThroughOwnerOrdinal != want.ThroughOwnerOrdinal {
		t.Errorf("cutoff = %+v, want %+v", cutoff, want)
	}

	exec, err := ProjectExecutionFromStore(store, reader, cutoff)
	if err != nil {
		t.Fatalf("ProjectExecutionFromStore: %v", err)
	}
	if exec.Status != ExecutionFailed {
		t.Errorf("status = %s, want failed", exec.Status)
	}
	if exec.Error != "ValueError: boom" {
		t.Errorf("error = %q, want the vector's error text", exec.Error)
	}
	if len(exec.Outputs) != 0 {
		t.Errorf("failed execution outputs = %v, want empty", exec.Outputs)
	}
}

// TestTerminalFrontierLawRejectsNonTerminal pins the law: a frontier may only
// be published through a completed or failed fact.
func TestTerminalFrontierLawRejectsNonTerminal(t *testing.T) {
	store := newMemStore(t)
	execID := ExecutionIDFor("law:terminal:create", "execution")
	receipt, err := store.Append(TrustedAppendContext, CreateExecutionBatch(
		"law:terminal:create", execID, "Task", nil, "", nil,
	))
	if err != nil {
		t.Fatalf("Append: %v", err)
	}
	startedID := receipt.FactIDs[len(receipt.FactIDs)-1]

	_, err = PublishExecutionFrontier(store, TrustedAppendContext,
		"frontier:law:terminal", execID, startedID, "", "", nil)
	if err == nil {
		t.Fatal("frontier through a started fact was published, want rejection")
	}
	if !strings.Contains(err.Error(), "terminal lifecycle fact") {
		t.Errorf("error %q does not name the terminal-frontier law", err.Error())
	}
}

// TestProjectExecutionFoldStates walks the fold through pending → running →
// succeeded, checking that each terminal fact wins and that the synthesized
// cutoff carries the last fact when no frontier backs the slice.
func TestProjectExecutionFoldStates(t *testing.T) {
	store := newMemStore(t)
	execID := ExecutionIDFor("fold:run:create", "execution")

	create, err := store.Append(TrustedAppendContext, CreateExecutionBatch(
		"fold:run:create", execID, "FoldTask", map[string]any{"x": json.Number("1")}, "", nil,
	))
	if err != nil {
		t.Fatalf("create: %v", err)
	}

	pending, err := store.ReadOwnerPrefix(reader, execID, 99, ModeBoth)
	if err != nil {
		t.Fatalf("read pending: %v", err)
	}
	// created+started land in one batch, so the fold is running from the first
	// read; "pending" is a fold-internal state the both-mode requirement makes
	// unobservable — a declarations_only slice would show it, and is rejected.
	exec, err := ProjectExecution(pending, execID, nil)
	if err != nil {
		t.Fatalf("project running: %v", err)
	}
	if exec.Status != ExecutionRunning {
		t.Errorf("status = %s, want running (started lands with created)", exec.Status)
	}
	if exec.TaskRef != "FoldTask" || exec.Inputs["x"] != json.Number("1") {
		t.Errorf("running fold = task %q inputs %v", exec.TaskRef, exec.Inputs)
	}
	if exec.StartedFactID != create.FactIDs[1] {
		t.Errorf("started fact = %s, want %s", exec.StartedFactID, create.FactIDs[1])
	}

	complete, err := store.Append(TrustedAppendContext, CompleteExecutionBatch(
		"fold:run:complete", execID, map[string]any{"done": true},
		[]string{create.FactIDs[len(create.FactIDs)-1]},
	))
	if err != nil {
		t.Fatalf("complete: %v", err)
	}
	running, err := store.ReadOwnerPrefix(reader, execID, 99, ModeBoth)
	if err != nil {
		t.Fatalf("read terminal: %v", err)
	}
	exec, err = ProjectExecution(running, execID, nil)
	if err != nil {
		t.Fatalf("project terminal: %v", err)
	}
	if exec.Status != ExecutionSucceeded {
		t.Errorf("status = %s, want succeeded", exec.Status)
	}
	if exec.StartedFactID != create.FactIDs[1] {
		t.Errorf("started fact = %s, want %s", exec.StartedFactID, create.FactIDs[1])
	}
	if exec.TerminalFactID != complete.FactIDs[0] {
		t.Errorf("terminal fact = %s, want %s", exec.TerminalFactID, complete.FactIDs[0])
	}
	if exec.Cutoff.ThroughFactID != complete.FactIDs[0] {
		t.Errorf("synthesized cutoff through = %s, want the terminal fact", exec.Cutoff.ThroughFactID)
	}
	if exec.Cutoff.FrontierID != "" {
		t.Errorf("synthesized cutoff frontier = %q, want empty", exec.Cutoff.FrontierID)
	}
}

// TestProjectExecutionRequiresBothModes closes the plan-01 law "projections
// fail on incompatible mode filter": a captures_only slice cannot feed a
// fold that needs the created declaration.
func TestProjectExecutionRequiresBothModes(t *testing.T) {
	store := newMemStore(t)
	execID := ExecutionIDFor("mode:run:create", "execution")
	_, err := store.Append(TrustedAppendContext, CreateExecutionBatch(
		"mode:run:create", execID, "Task", nil, "", nil,
	))
	if err != nil {
		t.Fatalf("create: %v", err)
	}

	slice, err := store.ReadOwnerPrefix(reader, execID, 99, ModeCapturesOnly)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	_, err = ProjectExecution(slice, execID, nil)
	if !errors.Is(err, ErrProjectionMode) {
		t.Fatalf("captures_only slice fed to the fold: got %v, want ErrProjectionMode", err)
	}
}

type historyVectorChild struct {
	ExecutionID string `json:"execution_id"`
	TaskRef     string `json:"task_ref"`
	Status      string `json:"status"`
	Kind        string `json:"kind"`
	RelationID  string `json:"relation_id"`
	FrontierID  string `json:"frontier_id"`
}

type executionVectorHistory struct {
	RunID           string                `json:"run_id"`
	ExecutionID     string                `json:"execution_id"`
	FrontierID      string                `json:"frontier_id"`
	TaskRefs        map[string]string     `json:"task_refs"`
	ParentOwnerPath []executionVectorFact `json:"parent_owner_path"`
	RootStatus      string                `json:"root_status"`
	RootTaskRef     string                `json:"root_task_ref"`
	Children        []historyVectorChild  `json:"children"`
	Published       []string              `json:"published"`
}
