package shepherd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

// These vectors are generated by the Python reference *store*, not by Go.
//
// Generator: `testdata/generate_store_vectors.py`, which drives shepherd2's own
// SQLiteTraceStore against a fresh database per fixture and records every identity
// it allocates. Regenerate with:
//
//	python testdata/generate_store_vectors.py testdata/store_vectors_v0.json
//
// Digest-layer agreement does not prove the store agrees — the store *builds* the
// digest inputs. A difference in the witness plan, the retained-context payload or
// the context-id algorithm yields different ids from identical content, which is
// exactly what happened: record, witness and context ids all differed before this
// was fixed.

type storeVectorDoc struct {
	CanonicalVersion string        `json:"canonical_version"`
	Generator        string        `json:"generator"`
	SourceCommit     string        `json:"source_commit"`
	PythonVersion    string        `json:"python_version"`
	Vectors          []storeVector `json:"vectors"`
}

type storeVector struct {
	Label     string           `json:"label"`
	Note      string           `json:"note"`
	Batches   []vectorBatch    `json:"batches"`
	Frontiers []vectorFrontier `json:"frontiers"`
	Expected  vectorExpected   `json:"expected"`
}

type vectorBatch struct {
	AppendIntentID string        `json:"append_intent_id"`
	Groups         []vectorGroup `json:"groups"`
}

type vectorGroup struct {
	TraceOwnerID    string         `json:"trace_owner_id"`
	RetainedContext map[string]any `json:"retained_context"`
	CausalParents   []string       `json:"causal_parents"`
	FactDrafts      []vectorDraft  `json:"fact_drafts"`
}

type vectorDraft struct {
	Mode              string         `json:"mode"`
	SchemaRef         string         `json:"schema_ref"`
	Payload           map[string]any `json:"payload"`
	KindLabel         string         `json:"kind_label"`
	AppendLocalID     *string        `json:"append_local_id"`
	CausedByFactIDs   []string       `json:"caused_by_fact_ids"`
	CausedByLocalRefs []string       `json:"caused_by_local_refs"`
}

type vectorFrontier struct {
	AfterBatch         int    `json:"after_batch"`
	FrontierID         string `json:"frontier_id"`
	TargetTraceOwnerID string `json:"target_trace_owner_id"`
	ThroughLastFactOf  int    `json:"through_last_fact_of"`
}

type vectorExpected struct {
	Receipts    []expectedReceipt `json:"receipts"`
	FrontierIDs []string          `json:"frontier_ids"`
	OwnerPaths  map[string]any    `json:"owner_paths"`
}

type expectedReceipt struct {
	AppendIntentID     string           `json:"append_intent_id"`
	FactIDs            []string         `json:"fact_ids"`
	CommitReceipts     []string         `json:"commit_receipts"`
	ContextReceipts    []string         `json:"context_receipts"`
	OwnerOrdinalRanges map[string][]int `json:"owner_ordinal_ranges"`
	CausalEdges        [][]string       `json:"causal_edges"`
}

// loadStoreVectors decodes with UseNumber, because payloads feed the record digest
// and the int/float distinction has to survive the round trip: JSON `1` and `1.0`
// canonicalise differently.
func loadStoreVectors(t *testing.T) storeVectorDoc {
	t.Helper()
	data, err := os.ReadFile("testdata/store_vectors_v0.json")
	if err != nil {
		t.Fatalf("read store vectors: %v", err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var doc storeVectorDoc
	if err := dec.Decode(&doc); err != nil {
		t.Fatalf("parse store vectors: %v", err)
	}
	return doc
}

func vectorStrings(v any) []string {
	list, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(list))
	for _, item := range list {
		s, _ := item.(string)
		out = append(out, s)
	}
	return out
}

func vectorString(v any) string {
	s, _ := v.(string)
	return s
}

func vectorInt(v any) int {
	n, _ := v.(json.Number)
	i, _ := n.Int64()
	return int(i)
}

// TestStoreVectorsMatchPython is the acceptance test for plan 01 §4: replaying the
// reference store's fixtures must allocate identical identities.
func TestStoreVectorsMatchPython(t *testing.T) {
	doc := loadStoreVectors(t)

	if doc.CanonicalVersion != CanonicalVersion {
		t.Errorf("vector file canonical_version = %q, want %q", doc.CanonicalVersion, CanonicalVersion)
	}
	if doc.SourceCommit == "" || doc.SourceCommit == "unknown" {
		t.Error("vector file has no source_commit, so the vectors cannot be traced to a revision")
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("vector file contains no fixtures")
	}
	t.Logf("replaying %d fixtures from shepherd2@%.12s (Python %s)",
		len(doc.Vectors), doc.SourceCommit, doc.PythonVersion)

	for _, v := range doc.Vectors {
		t.Run(v.Label, func(t *testing.T) {
			replayStoreVector(t, v)
		})
	}
}

func replayStoreVector(t *testing.T, v storeVector) {
	t.Helper()

	store := newMemStore(t)
	contextIDs := map[[2]int]string{}

	for batchIndex, batchSpec := range v.Batches {
		groups := make([]AppendGroup, 0, len(batchSpec.Groups))
		for _, g := range batchSpec.Groups {
			groups = append(groups, buildVectorGroup(t, g, contextIDs))
		}

		receipt, err := store.Append(trustedAppend, AppendBatch{
			AppendIntentID: batchSpec.AppendIntentID,
			Groups:         groups,
		})
		if err != nil {
			t.Fatalf("batch %d (%s): %v", batchIndex, batchSpec.AppendIntentID, err)
		}

		if batchIndex >= len(v.Expected.Receipts) {
			t.Fatalf("batch %d has no expected receipt", batchIndex)
		}
		want := v.Expected.Receipts[batchIndex]
		compareReceipt(t, batchIndex, receipt, want)

		for gi, cid := range receipt.ContextReceipts {
			contextIDs[[2]int{batchIndex, gi}] = cid
		}

		for _, f := range v.Frontiers {
			if f.AfterBatch != batchIndex {
				continue
			}
			cut, err := store.PublishFrontier(trustedAppend, FrontierSpec{
				FrontierID:         f.FrontierID,
				TargetTraceOwnerID: f.TargetTraceOwnerID,
				ThroughFactID:      receipt.FactIDs[f.ThroughLastFactOf],
			})
			if err != nil {
				t.Fatalf("publish frontier %s: %v", f.FrontierID, err)
			}
			if cut.FrontierID != f.FrontierID {
				t.Errorf("frontier id = %q, want %q", cut.FrontierID, f.FrontierID)
			}
		}
	}

	compareOwnerPaths(t, store, v)
}

func buildVectorGroup(t *testing.T, g vectorGroup, contextIDs map[[2]int]string) AppendGroup {
	t.Helper()

	out := AppendGroup{
		TraceOwnerID:  g.TraceOwnerID,
		CausalParents: nonNilStrings(g.CausalParents),
	}

	if g.RetainedContext != nil {
		if raw, ok := g.RetainedContext["reuse_of_batch"]; ok {
			// Python passes a bare context id for reuse; Go's resolveGroupContext
			// recognises that as an id with no substrate ref.
			key := [2]int{vectorInt(raw), vectorInt(g.RetainedContext["reuse_of_group"])}
			id, ok := contextIDs[key]
			if !ok {
				t.Fatalf("reuse reference to batch %v group %v, which was never appended",
					key[0], key[1])
			}
			out.RetainedContext = &RetainedContext{ContextID: id}
		} else {
			out.RetainedContext = &RetainedContext{
				ActiveBindingRefs:       vectorStrings(g.RetainedContext["active_binding_refs"]),
				CapabilityWitnessRefs:   vectorStrings(g.RetainedContext["capability_witness_refs"]),
				SemanticEnvironmentRefs: vectorStrings(g.RetainedContext["semantic_environment_refs"]),
				VisibilityPolicyRefs:    vectorStrings(g.RetainedContext["visibility_policy_refs"]),
				SubstrateRef:            vectorString(g.RetainedContext["substrate_ref"]),
				Containment:             Containment(vectorString(g.RetainedContext["containment"])),
			}
		}
	}

	for _, d := range g.FactDrafts {
		draft := RecordDraft{
			Mode:              RecordMode(d.Mode),
			SchemaRef:         d.SchemaRef,
			Payload:           d.Payload,
			KindLabel:         d.KindLabel,
			CausedByFactIDs:   d.CausedByFactIDs,
			CausedByLocalRefs: d.CausedByLocalRefs,
		}
		if d.AppendLocalID != nil {
			draft.AppendLocalID = *d.AppendLocalID
		}
		out.FactDrafts = append(out.FactDrafts, draft)
	}
	return out
}

func compareReceipt(t *testing.T, batchIndex int, got AppendReceipt, want expectedReceipt) {
	t.Helper()

	if got.AppendIntentID != want.AppendIntentID {
		t.Errorf("batch %d intent = %q, want %q", batchIndex, got.AppendIntentID, want.AppendIntentID)
	}
	assertSameSequence(t, batchIndex, "fact_ids", got.FactIDs, want.FactIDs)
	assertSameSequence(t, batchIndex, "commit_receipts", got.CommitReceipts, want.CommitReceipts)
	assertSameSequence(t, batchIndex, "context_receipts", got.ContextReceipts, want.ContextReceipts)

	for owner, wantRange := range want.OwnerOrdinalRanges {
		gotRange, ok := got.OwnerRanges[owner]
		if !ok {
			t.Errorf("batch %d has no ordinal range for owner %q", batchIndex, owner)
			continue
		}
		if gotRange[0] != wantRange[0] || gotRange[1] != wantRange[1] {
			t.Errorf("batch %d owner %q range = %v, want %v", batchIndex, owner, gotRange, wantRange)
		}
	}
	if len(got.OwnerRanges) != len(want.OwnerOrdinalRanges) {
		t.Errorf("batch %d has %d owner ranges, want %d", batchIndex, len(got.OwnerRanges), len(want.OwnerOrdinalRanges))
	}

	gotEdges := make([]string, 0, len(got.CausalEdges))
	for _, e := range got.CausalEdges {
		gotEdges = append(gotEdges, e[0]+"->"+e[1])
	}
	wantEdges := make([]string, 0, len(want.CausalEdges))
	for _, e := range want.CausalEdges {
		wantEdges = append(wantEdges, e[0]+"->"+e[1])
	}
	assertSameSequence(t, batchIndex, "causal_edges", gotEdges, wantEdges)
}

func compareOwnerPaths(t *testing.T, store *SQLiteTraceStore, v storeVector) {
	t.Helper()

	labels, _ := v.Expected.OwnerPaths["_kind_labels"].(map[string]any)

	for owner, raw := range v.Expected.OwnerPaths {
		if owner == "_kind_labels" {
			continue
		}
		want := vectorStrings(raw)

		slice, err := store.ReadOwnerPrefix(reader, owner, 9999, ModeBoth)
		if err != nil {
			t.Fatalf("read owner %q: %v", owner, err)
		}
		assertSameStrings(t, fmt.Sprintf("owner_paths[%s]", owner), slice.FactIDs(), want)

		for _, fid := range want {
			rec, ok := slice.FactsByID[fid].(Record)
			if !ok || rec.View == nil {
				continue
			}
			if wantLabel, ok := labels[fid].(string); ok && rec.View.KindLabel != wantLabel {
				t.Errorf("record %s kind_label = %q, want %q", fid, rec.View.KindLabel, wantLabel)
			}
		}
	}
}

// assertSameStrings compares two sequences and reports the first difference.
func assertSameStrings(t *testing.T, what string, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s has %d entries, want %d\n got: %v\nwant: %v", what, len(got), len(want), got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("%s[%d] = %q, want %q", what, i, got[i], want[i])
		}
	}
}

// TestStoreVectorsCoverTheFixedDivergences guards against the fixture set being
// weakened, which would quietly un-verify the identities this exists to pin.
func TestStoreVectorsCoverTheFixedDivergences(t *testing.T) {
	doc := loadStoreVectors(t)

	joined := new(bytes.Buffer)
	for _, v := range doc.Vectors {
		joined.WriteString(v.Label)
		joined.WriteByte('\n')
		for _, r := range v.Expected.Receipts {
			for _, id := range r.FactIDs {
				joined.WriteString(id)
				joined.WriteByte('\n')
			}
			for _, id := range r.ContextReceipts {
				joined.WriteString(id)
				joined.WriteByte('\n')
			}
		}
	}
	all := joined.String()

	// "context:" is the prefix Python uses; "ctx:" was the wrong one, and seeing it
	// would mean the vectors were regenerated from the Go side by mistake.
	if !bytes.Contains([]byte(all), []byte("context:")) {
		t.Error("no context: ids in the vectors; the context-id algorithm is untested")
	}
	if bytes.Contains([]byte(all), []byte("ctx:")) {
		t.Error("vectors contain ctx: ids, which is the Go-side prefix, not Python's")
	}

	for _, label := range []string{
		"ordinary_witness_non_default_context",
		"retained_context_reuse_by_id",
		"multi_group_atomic_batch",
		"local_ref_resolution",
		"frontier_publish",
		"non_ascii_payload",
		"intent_replay",
	} {
		found := false
		for _, v := range doc.Vectors {
			if v.Label == label {
				found = true
			}
		}
		if !found {
			t.Errorf("fixture %q is missing; the case it covers is no longer verified", label)
		}
	}
}
